[Level 2 일반야구 + 테스트코드]
Hyune-c-mentoring/cosmic-baseball pull request #10
Opened 2024-06-05 03:44 UTC by mingMy-00

1. 테스트 코드 중 제가 게임을 조금 잘못 이해하여 작성하지 못한 게 2개 있습니다. (설명 써놓긴 했는데 저는 더블 스트라이크, 더블 볼이라는 개념이 처음부터 랜덤으로 나오지 못하도록 했습니다. 무조건 게임에는 스트라이크, 볼, 안타만 존재하고 거기서 스트라이크 후에 또 스트라이크일 때만 더블 스트라이크가 뜨도록 설정을 했습니다. 사실 그래서 enum class도 resultype이라는 enum을 하나 더 생성했었는데  [기존의 enum은 ball, strike, hit만 존재해야해서] 만약 게임 방식을 진행하는 데 있어 랜덤으로 더블 종류들도 나오도록 바꿔야할 거 같다 하시면 바꾸겠습니다!!]

2024-06-05 03:44 UTC, mingMy-00 commented
@Hyune-c 
pr 요청드립니다.

2024-06-05 05:02 UTC, Hyune-c requested changes
> 만약 게임 방식을 진행하는 데 있어 랜덤으로 더블 종류들도 나오도록 바꿔야할 거 같다 하시면 바꾸겠습니다!!

- 우주야구 lv1 의 요건을 보면 확률은 별도로 명시되어 있지 않습니다.
- 즉 마지막 줄 처럼 strike, ball 과 같이 처음부터 double 이 나오게 해도 됩니다.

지금의 상황은 기획자의 모호한 의도를 보고 모호하게 개발된 예 입니다.
이해를 못하는 것보다 잘못 이해하는 (곡해하는) 것이 더 무서운 이유이죠.

하지만 괜찮습니다. 실무에서도 업무 초기에 비일비재하게 생기는 일이며 소프트웨어 수정은 비교적 쉽기 때문 입니다.
기존에 만든 코드를 지워야 할 수도 있지만, TDD 를 한다는 생각으로 요건에 맞는 테스트 코드를 만들고 수정해보시면 좋을 것 같습니다.

---

![image](https://github.com/Hyune-c-mentoring/cosmic-baseball/assets/55722186/23d23a8e-7ac2-4aed-a2fd-044991d42385)

근데 테스트 코드가 많이 깨지는 것 같습니다..

2024-06-05 05:02 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseball/controller/BaseballController.java
>    }
- PlateAppearanceResult 가 null 로 초기 선언 되어야 할까요?
- PlateAppearanceResult 가 null 이 아니면 바로 return 하는 것은 어떨까요?

2024-06-05 05:02 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseball/entity/BaseballGame.java
> +    this.atBatInProgress = false;
- 점점 변수가 많아지고 있네요. 
- 변수에 at, in 등의 조사가 들어가고 있네요. 가독성이 떨어집니다.

보통 레거시 코드를 해치지 않으면서 로직을 `추가` 하고 싶을 때 이런 형태가 나타납니다.
슬슬 코드 스멜을 느끼셔야 됩니다.

2024-06-05 05:02 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseball/entity/BaseballGame.java
>    }
하나의 메서드가 2가지 일을 하고 있군요.
단일 책임 원칙을 말하시는 분도 있지만, 저도 사실 실무를 하다보면 이렇게 두가지 일을 함께 시키는 경우가 있습니다. 캡슐화란 이름으로 말이죠. 

이것을 분리할지 말지는 작업자의 의사에 맡깁니다. 다만 코드 스멜은 느끼셔야 됩니다.

2024-06-05 05:02 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseball/entity/BaseballGame.java
>    public boolean isGameEnd() {
일반야구 lv2 에는 타격과 타석이 구분되는 요건이 들어왔습니다.
- 그렇다면 이 메서드의 결과는 게임 종료가 아니라 타석 종료가 좀 더 적절하지 않을까요?
- 타석이 1개 뿐이라서 게임 종료와 동일하다고 하더라도 개념을 나누는 것을 추천 합니다.

2024-06-05 05:02 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseball/entity/BaseballGame.java
> +  public boolean hasReachedStrikeLimit() {
`nit` reachedStrikeLimit 또는 isReachedStrikeLimit 가 조금 더 잘 읽히지 않을까요? 
has 는 관습적으로 list 형 자료 구조의 내부를 체크할 때 쓰입니다.

2024-06-05 05:02 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseball/handler/ResultHandler.java
>  public class ResultHandler implements GameResultHandler {
string 을 enum 으로 바꾸는 행위가 꼭 별도 handler 가 필요한 일일까요?

2024-06-05 05:02 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseball/handler/ResultHandler.java
> +        return ResultType.DOUBLE_STRIKE;
언더바의 일관성이 지켜지지 않고 있습니다.
이런 위험성 때문에 실무에서는 string 변환을 매우 보수적으로 사용 합니다.

2024-06-05 05:02 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseball/util/PlateAppearanceResult.java
> +}
👍

2024-06-05 05:02 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseball/util/BattingResult.java
> +      lastResult -> lastResult.equals("BALL") ? "DOUBLEBALL" : "BALL"), HIT(lastResult -> "HIT");
```suggestion
    STRIKE(lastResult -> lastResult.equals("STRIKE") ? "DOUBLESTRIKE" : "STRIKE"),
    BALL(lastResult -> lastResult.equals("BALL") ? "DOUBLEBALL" : "BALL"),
    HIT(lastResult -> "HIT"),
    ;
```
`nit`

2024-06-05 05:02 UTC, Hyune-c commented on src/main/resources/application.yml
> +  port: 8083
뭔가 하나씩 늘어나고 있네요 ㅋㅋ

2024-06-06 17:07 UTC, mingMy-00 reviewed
테스트코드 보고 놀랬습니담.. 제 패키지에서는 Level2 normal 야구 테스트는 다 정상 작동하는데 왜일까요 ..? 그런데 코드를 수정하면서 level 1도 테스트코드가 잘 작동하지 않더라구요!! (제대로 확인을 못했습니다.) 

그래서 
1. 테스트 코드 수정
2. 게임 룰 더블도 랜덤으로 나오도록 

맞춰서 수정하겠습니다 !

2024-06-06 17:07 UTC, mingMy-00 commented on src/main/java/com/hyunec/cosmicbaseball/entity/BaseballGame.java
> +    this.atBatInProgress = false;
그럼 명사가 가장 좋은 변수명일까요 ??

2024-06-06 17:07 UTC, mingMy-00 commented on src/main/java/com/hyunec/cosmicbaseball/entity/BaseballGame.java
>    }
코드 스멜이 안좋은 코드 작성 습관말씀 하시는거죠. !! 
저도 사실 분리하는 게 좋을 것 같다고 생각은 했는데 method가 너무 class 하나에 많아지는 것 같이 느껴져서요 class를 분리해야 할 것 같기더합니다..

2024-06-06 17:07 UTC, mingMy-00 commented on src/main/java/com/hyunec/cosmicbaseball/entity/BaseballGame.java
> +  public boolean hasReachedStrikeLimit() {
isReachedStrikeLimit 좋은 것 같습니다. has는 다음에 list에서 사용할 일이 있다면 사용해보겠습니다.

2024-06-06 17:07 UTC, mingMy-00 commented on src/main/java/com/hyunec/cosmicbaseball/handler/ResultHandler.java
>  public class ResultHandler implements GameResultHandler {
처음부터 그냥 Enum 클래스를 사용해도 될 것 같습니다. 저번에는 비즈니스 로직과 서비스 로직이 같이 있었어서 그거를 분리하는 과정에서 String을 사용하던 거 까지는 개선 못한 것 같습니다. !!!

2024-06-06 17:07 UTC, mingMy-00 commented on src/main/java/com/hyunec/cosmicbaseball/handler/ResultHandler.java
> +        return ResultType.DOUBLE_STRIKE;
다음 pr때는 String을 최대한 덜 쓰는 걸로 해보겠습니다 !! 사실 enum class에 double 값을 넣지 못해서 String으로 어쩔 수 없이 처리했었는데 이번에 바로 고치려고합니다 ㅠㅠ

2024-06-06 17:07 UTC, mingMy-00 commented on src/main/java/com/hyunec/cosmicbaseball/util/BattingResult.java
> +      lastResult -> lastResult.equals("BALL") ? "DOUBLEBALL" : "BALL"), HIT(lastResult -> "HIT");
혹시 멘토님도 google init를 사용하시나요 ?? (궁금해서요!!)

2024-06-06 17:07 UTC, mingMy-00 commented on src/main/resources/application.yml
> +  port: 8083
근본적으로 port kill을 해야하는데 테스트 할 때 빨리 하려고하다가 ㅎㅎ...... 다시 돌려놓겠습니다 !

2024-06-06 17:07 UTC, mingMy-00 commented on src/main/java/com/hyunec/cosmicbaseball/controller/BaseballController.java
>    }
그렇게 말씀하시니까 null을 굳이 보내줄 필요가 없다는 생각이 들긴합니다 !! 바로 return하는 게 좋을 것 같아요

2024-06-06 17:07 UTC, mingMy-00 commented on src/main/java/com/hyunec/cosmicbaseball/entity/BaseballGame.java
>    public boolean isGameEnd() {
제가 야구 룰을 잘 몰라서 룰 검색하면서 해서 그 개념에 대해서는 정확하게 생각을 못한 것 같아요 !! ㅜㅜ 말씀하신 게 맞는 거 같습니다 !!!!

2024-06-06 17:15 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseball/entity/BaseballGame.java
> +    this.atBatInProgress = false;
이건 정답이 없기 때문에 스스로 고민해보시는 것을 권장 합니다.

fyi.
- https://google.github.io/styleguide/javaguide.html#s5-naming
- 좋은 변수명 짓기. 등을 키워드로 검색

2024-06-06 17:16 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseball/util/BattingResult.java
> +      lastResult -> lastResult.equals("BALL") ? "DOUBLEBALL" : "BALL"), HIT(lastResult -> "HIT");
넹. 자바 썻을 때는 저도 google style guide 를 적용 했었습니다.

2024-06-13 11:07 UTC, closed without merging