[Level 1 우주야구게임] 게임 + 테스트
Hyune-c-mentoring/cosmic-baseball pull request #8
Opened 2024-05-26 15:35 UTC by mingMy-00

우선 기능은 돌아가는 상태인데요

1. IF ELSE 고민 
=> resultHandler에 if else가 가독성을 해치는거 같아 각 결과마다 class를 나누려했습니다. (strikeHandler, ballHandler 이런식으로) 그렇게 나누려고한 이유는 언젠가 책에서 혹은 강의에서 class를 많이 나눌 수록 유지보수에 좋다 (한 class에서 단일책임원칙을 위해서 !!) 아무튼 그 내용에 저도 동의를 많이 해서 그렇게 하려했으나 그렇게 하면 class가 3개나 더 생기는데 그게 더 좋은 방법일지 여쭤보고싶었습니다 !!

2. 같은 맥락으로 baseballGame에 method가 너무 많은거 같기도 한데요.. 이 부분도 따로 class로 빼는 게 좋을지!! (기능별로)

3. GOOGLE formater 적용했었는데 -가 또 뜬걸 보니까 제대로 적용이 안됐나봐요 다시 해보겠습니다 !!

2024-05-26 15:35 UTC, mingMy-00 commented
pr요청드립니다.

2024-05-27 11:48 UTC, Hyune-c requested changes
> IF ELSE 고민
=> resultHandler에 if else가 가독성을 해치는거 같아 각 결과마다 class를 나누려했습니다. (strikeHandler, ballHandler 이런식으로) 그렇게 나누려고한 이유는 언젠가 책에서 혹은 강의에서 class를 많이 나눌 수록 유지보수에 좋다 (한 class에서 단일책임원칙을 위해서 !!) 아무튼 그 내용에 저도 동의를 많이 해서 그렇게 하려했으나 그렇게 하면 class가 3개나 더 생기는데 그게 더 좋은 방법일지 여쭤보고싶었습니다 !!
같은 맥락으로 baseballGame에 method가 너무 많은거 같기도 한데요.. 이 부분도 따로 class로 빼는 게 좋을지!! (기능별로)

저는 나누는게 좋다고 생각합니다. 하지만 지금의 구조도 나쁘지는 않습니다. (이른 구조화를 피해라.)
- 만약 나눈다면, 타격 결과를 저장하는 책임과 게임을 진행하는 책임을 분리하지 싶습니다.
- fyi. CQRS

> 저번 핃백 반영해서 lombok 자체를 삭제하려했는데 까먹고 삭제를 안했네요 ㅠㅠㅠ !!!! 다음 pr때 바로 삭제하겠습니다.

다음 pr 말고 이번 pr 에서 개선점을 수정하면서 삭제해보시죠.

2024-05-27 11:48 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseball/controller/BaseballController.java
>          }
return 이 while 문 안에 있으면 반복되지 않고 1번만 작동되지 않나요?

2024-05-27 11:48 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseball/entity/BaseballGame.java
> +        List<String> possibleResults = Arrays.asList("스트라이크", "안타", "볼");
이 메서드는 호출될 때마다 possibleResults 를 생성하고 있네요. 어떤 문제가 있을까요.

---

안타와 볼의 순서가 바뀌었네요. 아래를 생각해봐주세요.
- list 는 순서가 있는 자료구조 입니다. 그렇다면 이런 순서 변경은 어떤 이슈가 생길까요?
- 각 element 가 유일하고 순서가 의미가 없다면 어떻게 바꿀 수 있을까요?
- enum 을 사용할 수 있을까요?

2024-05-27 11:48 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseball/entity/BaseballGame.java
> +                result = "더블볼";
"더블볼s" 로 바꿔달라는 요건이 들어오면 어떻게 될까요?

2024-05-27 11:48 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseball/entity/BaseballGame.java
>      }
메서드 이름과 내부 구현이 다른 것 같습니다.

2024-05-27 11:48 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseball/entity/BaseballGame.java
> +        ballCount ++;
```suggestion
        ballCount++;
```

이후 lint 관련은 언급하지 않습니다.

2024-05-27 11:48 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseball/handler/ResultHandler.java
>      }
`nit` 한줄로 끝나던 메서드가 if-else 로 복잡해지고 있군요. 아직은 그냥저냥 괜찮다고 볼 수도 있긴 합니다.

2024-05-27 11:48 UTC, Hyune-c commented on src/test/java/com/hyunec/cosmicbaseball/acceptancetest/CosmicBaseballLv1Test.java
> +        Assertions.assertThat(resultCounts.get("스트라이크"))
```suggestion
        assertThat(resultCounts.get("스트라이크"))
```

`nit`

2024-05-27 11:48 UTC, Hyune-c commented on src/test/java/com/hyunec/cosmicbaseball/acceptancetest/CosmicBaseballLv1Test.java
> +        int tolerance     = (int) (numberOfSwings * 0.05); // 허용 오차: 5%
확률을 테스트하기 위해 오차 범위를 허용하는 것을 선택하셨네요. 재미있는 접근이지만 `비결정적 테스트` 의 위험성이 내포되어 있습니다.

2024-05-27 11:48 UTC, Hyune-c commented on src/test/java/com/hyunec/cosmicbaseball/acceptancetest/CosmicBaseballLv1Test.java
> +        for (int i = 0; i < numberOfSwings; i++) {
fyi. enhanced for loop

2024-05-28 16:22 UTC, mingMy-00 commented on src/main/java/com/hyunec/cosmicbaseball/entity/BaseballGame.java
> +        List<String> possibleResults = Arrays.asList("스트라이크", "안타", "볼");
1.  호출될 때마다 possibleResults 를 생성 => 불필요한 메모리 사용이 증가할 것 같습니다. 반복문 밖에서 객체를 호출해주어야 할 것 같아요!!

2. 리스트는 순서가 있기 때문에 만약, 이 순서로 값을 추출해서 사용하고 있는 곳이 있다면,  (순서에 의존한다면) 예기치 않은 결과의 오류가 생길 것 같습니답.

3. 저 야구게임처럼 element가 유일하고 순서가 의미가 없다면 enum을 사용할 수 있을 것 같습니당. 
enum이 상수로 저장하기도 하고 순서가 의미없을 때 사용 하기에 좋기 때문에 (찾아봤습니답) 제가 하는 list보다는 enum이 더 좋을 것 같다는 생각이 듭니담.

2024-05-28 16:22 UTC, mingMy-00 commented on src/main/java/com/hyunec/cosmicbaseball/entity/BaseballGame.java
> +                result = "더블볼";
더블볼s라는 문자열로 제가 직접 찾아가서 바꿔줘야 합니답. 근데 어차피 정해져있는 결과이기 때문에 enum 을 만약 사용한다면, 결과만 모아놓은 enum이 따로 있기 때문에 바꿔주는 거 자체의 유지보수에 도움이 될 것 같다는 생각이듭니담.

2024-05-28 16:22 UTC, mingMy-00 commented on src/main/java/com/hyunec/cosmicbaseball/entity/BaseballGame.java
>      }
isThreeStrikes가 아니라 그냥 저 둘의 메소드 자체가 isGameEnd메소드고 안에서 로직을 처리해도 괜찮을 것 같다는 생각이 듭니다. 애초에 둘 다 게임이 끝났는지 확인하는로직이라서 !!

2024-05-28 16:22 UTC, mingMy-00 commented on src/main/java/com/hyunec/cosmicbaseball/entity/BaseballGame.java
> +        ballCount ++;
구글 리팩토링 다시 적용했습니담..ㅜㅠㅠㅠ

2024-05-28 16:22 UTC, mingMy-00 commented on src/main/java/com/hyunec/cosmicbaseball/handler/ResultHandler.java
>      }
저는 다소 이 if else가 복잡하다고 생각이 들긴하는데 이른 구조화를 피하라 하신 말씀에 냅두고 있습니당. 
이른 구조화를 피하라는 거는 처음부터 구조를 생각하며 개발하기엔 무리가 있어서일까요 ?? 아니면 변수(경우의 수)가 많기 때문일까요

2024-05-28 16:22 UTC, mingMy-00 commented on src/test/java/com/hyunec/cosmicbaseball/acceptancetest/CosmicBaseballLv1Test.java
> +        for (int i = 0; i < numberOfSwings; i++) {
생각해보니까 이건 인덱스가 필요없어서 향상된 포문 쓰는 게 좋겠네용....가독성 측면 ,..,,. 감사합니다 !!!!

2024-05-28 16:22 UTC, mingMy-00 commented on src/test/java/com/hyunec/cosmicbaseball/acceptancetest/CosmicBaseballLv1Test.java
> +        int tolerance     = (int) (numberOfSwings * 0.05); // 허용 오차: 5%
항상 결과가 동일하게 나올 수는 없다고 생각하긴 했습니당. 그렇다면 비결정적 테스트의 위험성을 내재하기 않기 위한 방법으로 시드를 설정해주는 게 효과가 있을까요 ?? 시드를 사용하면 동일한 순서의 무작위 수를 생성할 수 있다고 해서 그나마 한 테스트에 만약 오류가 발생했을 경우 그를 확인하기는 조금은 더 용이할 수 있을 것 같아서요!!!

-

2024-05-28 16:22 UTC, mingMy-00 commented on src/test/java/com/hyunec/cosmicbaseball/acceptancetest/CosmicBaseballLv1Test.java
> +        Assertions.assertThat(resultCounts.get("스트라이크"))
static import 하는걸 ..... 당장 적용하겠습니담

2024-05-28 16:22 UTC, mingMy-00 commented on src/test/java/com/hyunec/cosmicbaseball/acceptancetest/CosmicBaseballLv1Test.java
> +        Assertions.assertThat(resultCounts.get("스트라이크"))
저번 pr때 말씀해주셨는데 이번에 제 질문 올리려고 한 pr 때문에 인지를 못하고있었습니다!! ㅠㅠ

2024-05-28 16:47 UTC, Hyune-c reviewed
코멘트는 주셨지만 아직 수정된 commit 은 올라오지 않았네요.
수정된 commit 이 올라오면 최종 리뷰 후 approve 할 수 있도록 하겠습니다.

2024-05-28 16:47 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseball/entity/BaseballGame.java
>      }
현재 로직상 메서드 이름에서는 3 strike 만을 체크할 것 같지만,
- 메서드 내부는 4 strike 도 true 가 반환됩니다.

`nit` 지금은 흐름상 4 strike 가 될 수 없을테니 괜찮아보이지만 위험성을 내포하고 있는 로직 입니다.

2024-05-28 16:47 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseball/handler/ResultHandler.java
>      }
후자에 가깝습니다. 경험 많은 도메인 전문가라도 새로운 기술이나 프로덕트로 생기는 변화를 예측하기는 힘드니까요.

2024-05-28 16:47 UTC, Hyune-c commented on src/test/java/com/hyunec/cosmicbaseball/acceptancetest/CosmicBaseballLv1Test.java
> +        int tolerance     = (int) (numberOfSwings * 0.05); // 허용 오차: 5%
네 그런 방법도 있습니다. 하지만 원칙적인 방법으로는
- 랜덤성이 있는 로직을 분리 합니다.
    - 해당 로직의 fake 객체를 만들어 항상 균일한 결과가 나오게 합니다.

조금 다른 방향이지만 중요도가 적은 비결정적 테스트는 생략하기도 합니다. 
- 저도 이런 경우가 없다고는 말 못하겠네요.. ㅠ

2024-05-29 16:55 UTC, closed without merging